/*

389. Find the Difference
Easy

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/

class Solution {
    public char findTheDifference(String s, String t) {
        Map<Character, Integer> map = new HashMap<>();
        for(char ch : s.toCharArray()) map.put(ch, map.containsKey(ch) ? map.get(ch) + 1: 1);
        for(char ch : t.toCharArray()){
            if(!map.containsKey(ch) || map.containsKey(ch) && map.get(ch) <= 0) return ch;
            map.put(ch, map.get(ch) - 1);
        }
        return 'a';
    }
}
