"""

389. Find the Difference
Easy

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        dict = {}
        for i in range(len(s)):
            if s[i] in dict:
                dict[s[i]] = dict[s[i]] + 1
            else:
                dict[s[i]] = 1
        
        for i in range(len(t)):
            if t[i] not in dict or dict[t[i]] <= 0:
                return t[i]
            dict[t[i]] = dict[t[i]] - 1
        return 'a'
